{% set condaforge_name = "python-devtools" %}
{% set pypi_name = "devtools" %}
{% set version = "0.9.0" %}


package:
  name: {{ condaforge_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/devtools-{{ version }}.tar.gz
  sha256: 86ede6e0273e023db766344d14098228785b48a80f31716f28e8b9453d52fa1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - executing >=0.8.0,<1.0.0
    - asttokens >=2.0.0,<3.0.0

test:
  imports:
    - devtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/python-devtools
  summary: Python's missing debug print command and other development tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
