{% set condaforge_name = "python-devtools" %}
{% set pypi_name = "devtools" %}
{% set version = "0.12.0" %}


package:
  name: {{ condaforge_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/devtools-{{ version }}.tar.gz
  sha256: b131ca6e50b913353e29fc2f4057c61f2882e501f406f10a50c1bd3b2becdc51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - python >=3.7
    - executing >=1.1.1
    - asttokens >=2.0.0,<3.0.0
    - pygments >=2.15.0

test:
  imports:
    - devtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/python-devtools
  summary: Python's missing debug print command and other development tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
