{% set condaforge_name = "python-devtools" %}
{% set pypi_name = "devtools" %}
{% set version = "0.10.0" %}


package:
  name: {{ condaforge_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/devtools-{{ version }}.tar.gz
  sha256: 6eb7c4fa7c4b90e5cfe623537a9961d1dc3199d8be0981802c6931cd8f02418f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - hatchling
  run:
    - python >=3.6
    - executing >=1.1.1
    - asttokens >=2.0.0,<3.0.0

test:
  imports:
    - devtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/python-devtools
  summary: Python's missing debug print command and other development tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
